version: '3'

services:
  application:
    build:
      context: ./
      dockerfile: application.dockerfile
    ports:
      - 3000:3000
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    env_file: ./.env

  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181