version: '3'

services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  arangodb:
    image: arangodb:latest
    ports:
      - 8529:8529
    volumes:
      - ./volumes/arangodb/data:/var/lib/arangodb3
      - ./volumes/arangodb/apps:/var/lib/arangodb3-apps
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./volumes/kafka:/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  # application:
  #   depends_on:
  #     - elasticsearch
  #     - arangodb
  #     - zookeeper
  #     - kafka
  #   build:
  #     context: ../
  #     dockerfile: ./docker/application.dockerfile
  #   ports:
  #     - 5000:5000
  #   restart: always
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   env_file: ../.env