### NOTE: To use this file VSC REST Client extension must be installed 

### Finds all Documents by index
GET http://localhost:5000/search<index>

### Finds a Document by index and id
GET http://localhost:5000/search/<index>/<document-id>